### ISSUE TITLE
Failed to load all task lists

### ISSUE THREAD

**Issue by JuanChiogna** [ukhan/add-to-ms-todo#22]
Task lists do not load. All tasks go to the default "Tasks" list instead.
I'm using the latest version of Windows 10 and tried both Edge and Chrome browsers.
Here's the debug info, though everything seems just fine.

{
  "Request": "GET https://outlook.office.com/api/v2.0/me/taskfolders?top=100",
  "Meta": "2021-10-29T14:15:12.241Z 5:3000 0.20.0"
}

{
  "Response": "Ok",
  "Meta": "2021-10-29T14:15:12.548Z"
}

{
  "Request": "POST https://outlook.office.com/api/v2.0/me/tasks",
  "Meta": "2021-10-29T14:15:17.829Z 5:null 0.20.0",
  "body": {
    "Subject": "Settings Add to Microsoft To Do",
    "Body": {
      "Content": "chrome-extension://loblkkbfciiklgoblkigehhghfjfjede/options.html",
      "ContentType": "Text"
    },
    "Importance": "Normal"
  }
}

{
  "Response": "Ok",
  "Meta": "2021-10-29T14:15:18.250Z"
}

![image](https://user-images.githubusercontent.com/71669762/139447600-7853ecfb-66f0-4f43-a440-6b8b3e776ff8.png)
![image](https://user-images.githubusercontent.com/71669762/139447764-64d875d9-a665-459f-b3de-9cd41d9232dd.png)

**Comment by ukhan** [comment]
To understand what's going on, I also need information from the extension's background page console.

Please do the following:
- enable saving of debugging information in the extension;
- go to the browser extension management page (chrome://extensions/);
- activate developer mode (in the upper right corner);
- click on the "background page" caption next to the Add to Microsoft To Do extension;
- open the pop-up window of the extension so that the lists are loaded;
- take a screenshot (sensitive information will remain hidden) of the extension's console background page.

It's going to look something like this:

![2021-11-03_14-48-15](https://user-images.githubusercontent.com/1316705/140063146-0ea75533-6ab8-4778-a5ca-0f36cb2d5ae9.png)

**Comment by JuanChiogna** [comment]
I took a couple screenshots and tried a few times, but both chunkFolders and folders seem empty. 

Is there anything else I can do to give you more info on the issue?

![image](https://user-images.githubusercontent.com/71669762/140074409-9ccb0114-0f8c-4bc2-a874-45706229cb2c.png)
![image](https://user-images.githubusercontent.com/71669762/140074441-25e47bc0-84d9-4cfd-878f-4eb15a6078d0.png)

**Comment by ukhan** [comment]
It means that the Microsoft API returned an empty list. Here, unfortunately, we are powerless.
P.S. The native application uses an internal API.

**Comment by JuanChiogna** [comment]
Well, that's unfortunate. Thanks for your time anyways! Really love the extension 😄
